name: SSH Test

on:
  workflow_dispatch:

jobs:
  ssh-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 55422 -H ssh.lorseg.com >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -p 55422 sego@ssh.lorseg.com "hostname && uptime"
